import Head from "next/head";

const Home = () => (
  <>
    <Head>
      <title>HOME | DAILY ALGO</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>DailyAlgo</main>
    <div>
      create-next-app create-next-app 으로 설치하면
      <br />
      1. 컴파일과 번들링이 자동으로 된다(webpack과 babel)
      <br />
      2. 자동 리프레쉬 기능으로 수정하면 화면에 바로 반영된다.
      <br />
      3. 서버사이드 렌더링이 지원된다.
      <br />
      4. 스태틱 파일을 지원한다.
    </div>
  </>
);

export default Home;
